import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_excel(r"D:\Python\Battery charger\data\Voltage calibration.xlsx")

print(data.head())

v_4_i = pd.to_numeric(data.iloc[3:11,1])
v_8_i = pd.to_numeric(data.iloc[21:31,1])
v_12_i = pd.to_numeric(data.iloc[39:53,1])

adc_4_i = pd.to_numeric(data.iloc[3:11, 2])
adc_8_i = pd.to_numeric(data.iloc[21:31, 2])
adc_12_i = pd.to_numeric(data.iloc[39:53, 2])

v_4_ii = pd.to_numeric(data.iloc[4:13,11])
v_8_ii = pd.to_numeric(data.iloc[21:31,11])
v_12_ii = pd.to_numeric(data.iloc[39:53,11])

adc_4_ii = pd.to_numeric(data.iloc[4:13, 12])
adc_8_ii = pd.to_numeric(data.iloc[21:31, 12])
adc_12_ii = pd.to_numeric(data.iloc[39:53, 12]) 

vr_4 = pd.to_numeric(data.iloc[4:14, 15])
vr_8 = pd.to_numeric(data.iloc[21:32, 15])
vr_12 = pd.to_numeric(data.iloc[39:54, 15]) 

adcr_4 = pd.to_numeric(data.iloc[4:14, 16])
adcr_8 = pd.to_numeric(data.iloc[21:32, 16])
adcr_12 = pd.to_numeric(data.iloc[39:54, 16]) 
print(vr_8)

f1 = plt.figure()
plt.subplot(221)
ma,ba=np.polyfit(adc_4_i,v_4_i,1)
plt.scatter(adc_4_i,v_4_i)
lbl = "y=%fx%f"%(ma,ba)
plt.plot(adc_4_i, ma*adc_4_i+ ba,color='red', label=lbl)
plt.title("ADC Read at 4.2V Pin vs Voltage across it")
plt.xlabel("ADC read")
plt.ylabel("Voltage (V)")
plt.legend()
plt.grid(True)

plt.subplot(222)
#f2 = plt.figure()
mb,bb=np.polyfit(adc_8_i,v_8_i,1)
lbl = "y=%fx%f"%(mb,bb)
plt.scatter(adc_8_i,v_8_i)
plt.plot(adc_8_i, mb*adc_8_i+ bb,color='red', label=lbl)
plt.title("ADC Read at 8.4V Pin vs Voltage across it")
plt.xlabel("ADC read")
plt.ylabel("Voltage (V)")
plt.legend()
plt.grid(True)

plt.subplot(223)
#f3 = plt.figure()
mc,bc=np.polyfit(adc_12_i,v_12_i,1)
lbl = "y=%fx%f"%(mc,bc)
plt.scatter(adc_12_i,v_12_i)
plt.plot(adc_12_i, mc*adc_12_i+ bc,color='red', label=lbl)
plt.title("ADC Read at 12.6V Pin vs Voltage across it")
plt.xlabel("ADC read")
plt.ylabel("Voltage (V)")
plt.legend()
plt.grid(True)

f2 = plt.figure()
plt.subplot(221)
m,b=np.polyfit(adc_4_ii,v_4_ii,1)
plt.scatter(adc_4_ii,v_4_ii)
lbl = "y=%fx+%f"%(m,b)
plt.plot(adc_4_ii, m*adc_4_ii+ b,color='red', label=lbl)
plt.title("ADC Read at 4.2V Pin vs Voltage across it")
plt.xlabel("ADC read")
plt.ylabel("Voltage (V)")
plt.legend()
plt.grid(True)

plt.subplot(222)
#f2 = plt.figure()
m1,b1=np.polyfit(adc_8_ii,v_8_ii,1)
lbl = "y=%fx%f"%(m1,b1)
plt.scatter(adc_8_ii,v_8_ii)
plt.plot(adc_8_ii, m1*adc_8_ii+ b1,color='red', label=lbl)
plt.title("ADC Read at 8.4V Pin vs Voltage across it")
plt.xlabel("ADC read")
plt.ylabel("Voltage (V)")
plt.legend()
plt.grid(True)

plt.subplot(223)
#f3 = plt.figure()
m2,b2=np.polyfit(adc_12_ii,v_12_ii,1)
lbl = "y=%fx%f"%(m2,b2)
plt.scatter(adc_12_ii,v_12_ii)
plt.plot(adc_12_ii, m2*adc_12_ii+ b2,color='red', label=lbl)
plt.title("ADC Read at 12.6V Pin vs Voltage across it")
plt.xlabel("ADC read")
plt.ylabel("Voltage (V)")
plt.legend()
plt.grid(True)

adc = np.arange(0, 4100, 100, dtype= int)
f4_2 = ma*adc + ba
f4_2i = m*adc + b

f8_4 = mb*adc + bb
f8_4i = m1*adc + b1

f12_6 = mc*adc + bc
f12_6i = m2*adc + b2

f3=plt.figure()

plt.subplot(221)
plt.title('4.2V pin')
plt.plot(adc, f4_2, marker = 'o', label = 'initial calibration')
plt.plot(adc, f4_2i, color = 'red', marker = '^', label = 'recalibrated')
plt.xlabel('ADC values')
plt.ylabel('Voltage (V)')
plt.legend()
plt.subplot(222)
plt.title('8.4 V pin')
plt.plot(adc, f4_2, marker = 'o', label = 'initial calibration')
plt.plot(adc, f4_2i, color = 'red', marker = '^', label = 'recalibrated')
plt.xlabel('ADC values')
plt.ylabel('Voltage (V)')
plt.legend()
plt.subplot(223)
plt.title('12.6 V pin')
plt.plot(adc, f4_2, marker = 'o', label = 'initial calibration')
plt.plot(adc, f4_2i, color = 'red', marker = '^', label = 'recalibrated')
plt.xlabel('ADC values')
plt.ylabel('Voltage (V)')
plt.legend()

fr = plt.figure()
plt.subplot(221)
mr,br=np.polyfit(adcr_4,vr_4,1)
plt.scatter(adcr_4,vr_4)
lbl = "y=%fx%f"%(mr,br)
plt.plot(adcr_4, mr*adcr_4+ br,color='red', label=lbl)
plt.plot(adcr_4, m*adcr_4+ b,color='green', label= 'y=0.001187x-0.00451')
plt.title("ADC Read at 4.2V Pin vs Voltage across it")
plt.xlabel("ADC read")
plt.ylabel("Voltage (V)")
plt.legend()
plt.grid(True)

plt.subplot(222)
#f2 = plt.figure()
mr1,br1=np.polyfit(adcr_8,vr_8,1)
lbl = "y=%fx%f"%(mr1,br1)
plt.scatter(adcr_8,vr_8)
plt.plot(adcr_8, mr1*adcr_8+ br1,color='red', label=lbl)
plt.plot(adcr_8, m1*adcr_8+ b1,color='green', label= 'y=0.004437x-8.065')
plt.title("ADC Read at 8.4V Pin vs Voltage across it")
plt.xlabel("ADC read")
plt.ylabel("Voltage (V)")
plt.legend()
plt.grid(True)

plt.subplot(223)
#f3 = plt.figure()
mr2,br2=np.polyfit(adcr_12,vr_12,1)
lbl = "y=%fx%f"%(mr2,br2)
plt.scatter(adcr_12,vr_12)
plt.plot(adcr_12, m2*adcr_12+ b2,color='green', label='y=0.00685x-13.41')
plt.plot(adcr_12, mr2*adcr_12+ br2,color='red', label=lbl)
plt.title("ADC Read at 12.6V Pin vs Voltage across it")
plt.xlabel("ADC read")
plt.ylabel("Voltage (V)")
plt.legend()
plt.grid(True)

plt.show()